# Generated by Django 2.1.3 on 2018-11-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181128_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufactor',
            name='slug',
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('t', "It's Ok")], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='media/static/KalaImages/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181128 - 195615', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 195615'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 195615'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 195615'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('f', 'female'), ('o', 'Not mind'), ('m', 'Men')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('T', 'Packege sent'), ('B', 'Back to Store'), ('F', 'Packege Wait for send')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
