# Generated by Django 2.1.3 on 2018-11-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181128_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='media/static/KalaImages/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181128 - 211912', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 211912'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 211912'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 211912'),
        ),
    ]
