# Generated by Django 2.1.3 on 2018-11-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181128_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalainst',
            name='kala',
        ),
        migrations.AddField(
            model_name='kala',
            name='inst',
            field=models.ManyToManyField(help_text='اشیای موجود از این', related_name='kalainst', to='shop.KalaInst', verbose_name='اشیا'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='media/static/KalaImages/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181128 - 235111', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 235111'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 235111'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='media/static/KalaImages/no-image.jpg', null=True, upload_to='KalaImages/20181128 - 235111'),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('T', 'Packege sent'), ('F', 'Packege Wait for send'), ('B', 'Back to Store')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
