# Generated by Django 2.1.3 on 2018-11-29 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181128_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='inst',
        ),
        migrations.AddField(
            model_name='kalainst',
            name='kala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kalainst', to='shop.Kala'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('t', "It's Ok")], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181129 - 001517', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 001517'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 001517'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 001517'),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('T', 'Packege sent'), ('F', 'Packege Wait for send'), ('B', 'Back to Store')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
