# Generated by Django 2.1.3 on 2018-11-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20181129_0451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='PSize',
        ),
        migrations.RenameField(
            model_name='psize',
            old_name='size',
            new_name='sizeno',
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='shop.PSize'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kala',
            name='size',
            field=models.ManyToManyField(help_text='Select sizes for Product', to='shop.PSize'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('t', "It's Ok")], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181129 - 012334', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 012334'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 012334'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 012334'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('f', 'female'), ('m', 'Men'), ('o', 'Not mind')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('F', 'Packege Wait for send'), ('B', 'Back to Store'), ('T', 'Packege sent')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
