# Generated by Django 2.1.3 on 2018-11-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20181129_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181129 - 034449', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 034449'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 034449'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 034449'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('m', 'Men'), ('f', 'female'), ('o', 'Not mind')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='KhabarName',
            field=models.CharField(blank=True, choices=[('FALSE', 'عدم اشتراک در خبرنامه'), ('TRUE', 'مشترک خبرنامه')], default='FALSE', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('F', 'Packege Wait for send'), ('B', 'Back to Store'), ('T', 'Packege sent')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
