# Generated by Django 2.1.3 on 2018-11-29 15:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20181129_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='desc',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181129 - 155340', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 155340'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 155340'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181129 - 155340'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('m', 'Men'), ('o', 'Not mind'), ('f', 'female')], default='o', max_length=1),
        ),
    ]
