# Generated by Django 2.1.3 on 2018-12-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20181129_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Product Colors'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact us Table'},
        ),
        migrations.AlterModelOptions(
            name='kala',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='kalacat',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='kalainst',
            options={'verbose_name_plural': 'Product Instances'},
        ),
        migrations.AlterModelOptions(
            name='manufactor',
            options={'verbose_name_plural': 'Manufactors'},
        ),
        migrations.AlterModelOptions(
            name='myusers',
            options={'verbose_name_plural': 'Normal Users'},
        ),
        migrations.AlterModelOptions(
            name='psize',
            options={'verbose_name_plural': 'Product Sizes'},
        ),
        migrations.AlterModelOptions(
            name='salled',
            options={'verbose_name_plural': 'Salled'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name_plural': 'State Table'},
        ),
        migrations.AddField(
            model_name='cart',
            name='Payed',
            field=models.CharField(choices=[('F', 'Not Payed'), ('T', 'Payed')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181202 - 025330', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 025330'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 025330'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 025330'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('m', 'Men'), ('s', 'Special for sports'), ('f', 'female'), ('o', 'Not mind')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='KhabarName',
            field=models.CharField(blank=True, choices=[('TRUE', 'مشترک خبرنامه'), ('FALSE', 'عدم اشتراک در خبرنامه')], default='FALSE', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='salled',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('T', 'Packege sent'), ('F', 'Packege Wait for send'), ('B', 'Back to Store')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
