# Generated by Django 2.1.3 on 2018-12-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20181202_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='salled',
            name='FollowUpCode',
            field=models.CharField(default='1620181202031628', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Payed',
            field=models.CharField(choices=[('F', 'Not Payed'), ('T', 'Payed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('t', "It's Ok"), ('w', 'Waiting')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181202 - 031628', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 031628'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 031628'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 031628'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('m', 'Men'), ('s', 'Special for sports'), ('o', 'Not mind'), ('f', 'female')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('F', 'Packege Wait for send'), ('T', 'Packege sent'), ('B', 'Back to Store')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
