# Generated by Django 2.1.3 on 2018-12-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20181202_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181202 - 031634', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 031634'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 031634'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 031634'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('o', 'Not mind'), ('m', 'Men'), ('f', 'female'), ('s', 'Special for sports')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='salled',
            name='FollowUpCode',
            field=models.CharField(default='2520181202031634', max_length=20),
        ),
        migrations.AlterField(
            model_name='salled',
            name='sent',
            field=models.CharField(choices=[('T', 'Packege sent'), ('B', 'Back to Store'), ('F', 'Packege Wait for send')], default='F', help_text='Is package sent?', max_length=1, verbose_name='Send Status'),
        ),
    ]
