# Generated by Django 2.1.3 on 2018-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20181202_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Payed',
            field=models.CharField(choices=[('T', 'Payed'), ('F', 'Not Payed')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('w', 'Waiting'), ('t', "It's Ok")], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic0',
            field=models.ImageField(default='static/no-image.jpg', height_field='imageheigth', upload_to='KalaImages/20181202 - 034613', width_field='imagewidth'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic1',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 034613'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic2',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 034613'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='pic3',
            field=models.ImageField(blank=True, default='static/no-image.jpg', null=True, upload_to='KalaImages/20181202 - 034613'),
        ),
        migrations.AlterField(
            model_name='kalacat',
            name='gen',
            field=models.CharField(choices=[('f', 'female'), ('s', 'Special for sports'), ('o', 'Not mind'), ('m', 'Men')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='salled',
            name='FollowUpCode',
            field=models.CharField(default='5020181202034613', max_length=20),
        ),
    ]
